
package com.fitnessplayground.model.mindbody.api.site;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Site_x0020_ServiceSoap", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SiteX0020ServiceSoap {


    /**
     * Gets a list of sites.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetSitesResult
     */
    @WebMethod(operationName = "GetSites", action = "http://clients.mindbodyonline.com/api/0_5/GetSites")
    @WebResult(name = "GetSitesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetSites", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetSites")
    @ResponseWrapper(localName = "GetSitesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetSitesResponse")
    public GetSitesResult getSites(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetSitesRequest request);

    /**
     * Gets a list of locations.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetLocationsResult
     */
    @WebMethod(operationName = "GetLocations", action = "http://clients.mindbodyonline.com/api/0_5/GetLocations")
    @WebResult(name = "GetLocationsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetLocations", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetLocations")
    @ResponseWrapper(localName = "GetLocationsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetLocationsResponse")
    public GetLocationsResult getLocations(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetLocationsRequest request);

    /**
     * Gets an activation code.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetActivationCodeResult
     */
    @WebMethod(operationName = "GetActivationCode", action = "http://clients.mindbodyonline.com/api/0_5/GetActivationCode")
    @WebResult(name = "GetActivationCodeResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetActivationCode", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetActivationCode")
    @ResponseWrapper(localName = "GetActivationCodeResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetActivationCodeResponse")
    public GetActivationCodeResult getActivationCode(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetActivationCodeRequest request);

    /**
     * Gets a list of programs.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetProgramsResult
     */
    @WebMethod(operationName = "GetPrograms", action = "http://clients.mindbodyonline.com/api/0_5/GetPrograms")
    @WebResult(name = "GetProgramsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetPrograms", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetPrograms")
    @ResponseWrapper(localName = "GetProgramsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetProgramsResponse")
    public GetProgramsResult getPrograms(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetProgramsRequest request);

    /**
     * Gets a list of session types.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetSessionTypesResult
     */
    @WebMethod(operationName = "GetSessionTypes", action = "http://clients.mindbodyonline.com/api/0_5/GetSessionTypes")
    @WebResult(name = "GetSessionTypesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetSessionTypes", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetSessionTypes")
    @ResponseWrapper(localName = "GetSessionTypesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetSessionTypesResponse")
    public GetSessionTypesResult getSessionTypes(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetSessionTypesRequest request);

    /**
     * Gets a list of resources.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetResourcesResult
     */
    @WebMethod(operationName = "GetResources", action = "http://clients.mindbodyonline.com/api/0_5/GetResources")
    @WebResult(name = "GetResourcesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetResources", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetResources")
    @ResponseWrapper(localName = "GetResourcesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetResourcesResponse")
    public GetResourcesResult getResources(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetResourcesRequest request);

    /**
     * Gets a list of relationships.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetRelationshipsResult
     */
    @WebMethod(operationName = "GetRelationships", action = "http://clients.mindbodyonline.com/api/0_5/GetRelationships")
    @WebResult(name = "GetRelationshipsResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetRelationships", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetRelationships")
    @ResponseWrapper(localName = "GetRelationshipsResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetRelationshipsResponse")
    public GetRelationshipsResult getRelationships(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetRelationshipsRequest request);

    /**
     * Gets all resources schedule.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetResourceScheduleResult
     */
    @WebMethod(operationName = "GetResourceSchedule", action = "http://clients.mindbodyonline.com/api/0_5/GetResourceSchedule")
    @WebResult(name = "GetResourceScheduleResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetResourceSchedule", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetResourceSchedule")
    @ResponseWrapper(localName = "GetResourceScheduleResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetResourceScheduleResponse")
    public GetResourceScheduleResult getResourceSchedule(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetResourceScheduleRequest request);

    /**
     * Reserves a resource.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.ReserveResourceResult
     */
    @WebMethod(operationName = "ReserveResource", action = "http://clients.mindbodyonline.com/api/0_5/ReserveResource")
    @WebResult(name = "ReserveResourceResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "ReserveResource", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.ReserveResource")
    @ResponseWrapper(localName = "ReserveResourceResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.ReserveResourceResponse")
    public ReserveResourceResult reserveResource(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        ReserveResourceRequest request);

    /**
     * Gets a list of active mobile providers.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetMobileProvidersResult
     */
    @WebMethod(operationName = "GetMobileProviders", action = "http://clients.mindbodyonline.com/api/0_5/GetMobileProviders")
    @WebResult(name = "GetMobileProvidersResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetMobileProviders", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetMobileProviders")
    @ResponseWrapper(localName = "GetMobileProvidersResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetMobileProvidersResponse")
    public GetMobileProvidersResult getMobileProviders(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetMobileProvidersRequest request);

    /**
     * Gets a list of prospect stages for a site.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetProspectStagesResult
     */
    @WebMethod(operationName = "GetProspectStages", action = "http://clients.mindbodyonline.com/api/0_5/GetProspectStages")
    @WebResult(name = "GetProspectStagesResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetProspectStages", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetProspectStages")
    @ResponseWrapper(localName = "GetProspectStagesResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetProspectStagesResponse")
    public GetProspectStagesResult getProspectStages(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetProspectStagesRequest request);

    /**
     * Gets a list of prospect stages for a site.
     * 
     * @param request
     * @return
     *     returns com.fitnessplayground.model.mindbody.api.site.GetGendersResult
     */
    @WebMethod(operationName = "GetGenders", action = "http://clients.mindbodyonline.com/api/0_5/GetGenders")
    @WebResult(name = "GetGendersResult", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
    @RequestWrapper(localName = "GetGenders", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetGenders")
    @ResponseWrapper(localName = "GetGendersResponse", targetNamespace = "http://clients.mindbodyonline.com/api/0_5", className = "com.fitnessplayground.model.mindbody.api.site.GetGendersResponse")
    public GetGendersResult getGenders(
        @WebParam(name = "Request", targetNamespace = "http://clients.mindbodyonline.com/api/0_5")
        GetGendersRequest request);

}
